
spring.jpa.hibernate.ddl-auto: update
spring.datasource.url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/${MYSQL_DB:locations}
spring.datasource.username: ${MYSQL_USER:locations_user}
spring.datasource.password: ${MYSQL_PASSWORD:LocationsUserPassword}
spring.datasource.driver-class-name: com.mysql.jdbc.Driver
#spring.jpa.show-sql: true

spring.flyway.locations: classpath:flyway/mysql/migration

flyway.locations: classpath:resources/flyway/mysql/migration
